import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.4.1"

    const val com_squareup_retrofit2: String = "2.9.0"

    const val androidx_databinding: String = "4.1.1"

    const val androidx_room: String = "2.2.5"

    const val com_android_tools_build_gradle: String = "4.1.1"

    const val androidx_test_ext_junit: String = "1.1.2"

    const val junit_junit: String = "4.13.1"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val kotlin_annotation_processing_gradle: String = "1.4.20"

    const val retrofit2_kotlin_coroutines_adapter: String = "0.9.2"

    const val navigation_safe_args_gradle_plugin: String = "2.3.1"

    const val kotlin_android_extensions_runtime: String = "1.4.20"

    const val kotlin_android_extensions: String = "1.4.20"

    const val koin_androidx_viewmodel: String = "2.2.1"

    const val navigation_fragment_ktx: String = "2.3.1"

    const val kotlin_gradle_plugin: String = "1.4.20"

    const val lifecycle_extensions: String = "2.2.0"

    const val logging_interceptor: String = "4.9.0"

    const val kotlin_stdlib_jdk7: String = "1.4.20"

    const val paging_runtime_ktx: String = "2.1.2"

    const val navigation_ui_ktx: String = "2.3.1"

    const val constraintlayout: String = "2.0.4"

    const val work_runtime_ktx: String = "2.4.0"

    const val touchimageview: String = "3.0.3"

    const val espresso_core: String = "3.3.0"

    const val activity_ktx: String = "1.1.0"

    const val fragment_ktx: String = "1.2.5"

    const val moshi_kotlin: String = "1.11.0"

    const val recyclerview: String = "1.1.0"

    const val lint_gradle: String = "27.1.1"

    const val appcompat: String = "1.2.0"

    const val liveevent: String = "1.2.0"

    const val core_ktx: String = "1.3.2"

    const val material: String = "1.2.1"

    const val lottie: String = "3.5.0"

    const val aapt2: String = "4.1.1-6503028"

    const val glide: String = "4.11.0"

    /**
     * Current version: "6.7"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.7.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
